company_name = input()
company_address = input()
company_phone = input()
company_fax = input()
website = input()
first_name = input()
last_name = input()
age = input()
phone = input()

print(company_name)
print(f'Address: {company_address}')
print(f"Tel. {company_phone}")
print("Fax: ")
print(f"Web site: {website}")
print(f"Manager: {first_name} {last_name} (age: {age}, tel. {phone})")